Solidus/Solidus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
	path('account/', include('account.urls', namespace='account')),
    path('', include('navigator.urls', namespace='navigator')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Solidus/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('wildberries/add/<int:product_id>/', views.cart_add_wildberries, name='cart_add_wildberries'),
    path('pizzaroni/add/<int:product_id>/', views.cart_add_pizzaroni, name='cart_add_pizzaroni'),
    path('pizzaroni/remove/<int:product_id>/', views.cart_remove_pizzaroni, name='cart_remove_pizzaroni'),
    path('wildberries/remove/<int:product_id>/', views.cart_remove_wildberries, name='cart_remove_wildberries'),
]

Solidus/navigator/urls.py
from django.urls import path
from . import views

app_name = 'navigator'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('market_products/', views.market_products, name='market_products'),
    path('pizza_products/', views.pizza_products, name='pizza_products'),
    path('market/<int:id>/<slug:slug>/', views.wildberries_detail, name='wildberries_detail'),
    path('pizza/<int:id>/<slug:slug>/', views.pizzaroni_detail, name='pizzaroni_detail'),
]

Solidus/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
  path('wildberries/', views.order_create_wildberries, name='order_create_wildberries'),
  path('pizzaroni/', views.order_create_pizzaroni, name='order_create_pizzaroni'),
]

Solidus/cart/models.py
from django.db import models
from account.models import PhoneUser
from navigator.models import Pizzaroni, Wildberries
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

class CartModel(models.Model):
	phone_user = models.OneToOneField(PhoneUser, on_delete=models.CASCADE, related_name='cart')
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"Cart of {self.phone_user.phone_number}"

class CartItem(models.Model):
	cart = models.ForeignKey(CartModel, related_name='items', on_delete=models.CASCADE)
	content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type', 'object_id')
	quantity = models.PositiveIntegerField(default=1)
	price = models.DecimalField(max_digits=10, decimal_places=0)
	old_price = models.DecimalField(max_digits=10,
									decimal_places=0, null=True)

	def __str__(self):
		return f"{self.quantity} of {self.content_object.title}"

	@property
	def total_price(self):
		return self.quantity * self.price 
	
	@property
	def total_price_for_old(self):
		return self.quantity * self.old_price 

Solidus/cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
	quantity = forms.IntegerField(min_value=1, max_value=99, initial=1, label="")
	override = forms.BooleanField(required=False,
								 initial=False,
								 widget=forms.HiddenInput)
	def clean_quantity(self):
		"""Дополнительная проверка количества перед добавлением в корзину."""
		quantity = self.cleaned_data['quantity']
		if quantity > 99:
			raise forms.ValidationError("Вы не можете добавить больше 99 товаров.")
		return quantity

Solidus/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from navigator.models import Pizzaroni, Wildberries
from navigator.forms import SearchForm
from django.contrib.postgres.search import TrigramSimilarity
from functools import wraps
# Create your views here.

def verification_required(view_func):
	@wraps(view_func)
	def _wrapped_view(request, *args, **kwargs):
		if not request.session.get('is_profiled'):
			return redirect('account:handle_phone_number_submission')  # Перенаправляем на страницу верификации
		return view_func(request, *args, **kwargs)
	return _wrapped_view



@verification_required
@require_POST
def cart_add_pizzaroni(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Pizzaroni, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@verification_required
@require_POST
def cart_add_wildberries(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Wildberries, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@verification_required
@require_POST
def cart_remove_pizzaroni(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Pizzaroni, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@verification_required
@require_POST
def cart_remove_wildberries(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Wildberries, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@verification_required
def cart_detail(request):
	cart = Cart(request)
	pizzaroni_cart = cart.get_pizzaroni_items()
	total_price_pizzaroni = sum(item.total_price for item in pizzaroni_cart)
	total_price_for_old_pizzaroni = sum(item.total_price_for_old for item in pizzaroni_cart)
	wildberries_cart = cart.get_wildberries_items()
	total_price_wildberries = sum(item.total_price for item in wildberries_cart)
	total_price_for_old_wildberries = sum(item.total_price_for_old for item in wildberries_cart)

	pizzaroni_items = []
	for item in pizzaroni_cart:
		add_form = CartAddProductForm(initial={
			'quantity':item.quantity,
			'override':True
		})
		pizzaroni_items.append((item, add_form))
		
	wildberries_items = []
	for item in wildberries_cart:
		add_form = CartAddProductForm(initial={
			'quantity':item.quantity,
			'override':True
		})
		wildberries_items.append((item, add_form))


	form = SearchForm()
	query = None
	pizza_results = []
	market_results = []
	if 'query' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			query = form.cleaned_data['query']
			pizza_results = Pizzaroni.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
			market_results = Wildberries.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')

	return render(request, 'cart/detail.html', {'wildberries_items':wildberries_items,
												'total_price_wildberries':total_price_wildberries,
												'total_price_for_old_wildberries':total_price_for_old_wildberries,
												'pizzaroni_items':pizzaroni_items,
												'total_price_pizzaroni':total_price_pizzaroni,
												'total_price_for_old_pizzaroni':total_price_for_old_pizzaroni,
											   'form':form,
											   'query':query,
											   'pizza_results':pizza_results,
											   'market_results':market_results})

Solidus/cart/templates/cart/detail.html
{% extends "navigator/base.html" %}
{% load static %}
{% block title %}
 Корзина
{% endblock %}
{% block content %}
  {% if query %}
    <!-- Результат запроса Маркетплейсов -->
    <div class="row">
      {% if market_results %}
        <div class="row row-2">
          <h2>Маркетплейсы</h2>
        </div>
      {% endif %}
      {% for data in market_results %}
        <div class="col-4">
          
          <a href="{{ data.get_absolute_url }}">
            <img src="{{ data.picture_urls.0 }}">
          </a>
          
          <p>
            <a href="{{ data.get_absolute_url }}">
              {{ data.title|truncatechars:30 }}
            </a>
          </p>
          
          <p style="margin-top: -10px; margin-bottom: 3px;">
            <span style="font-size: 17px; color: black;">
              {{ data.price|floatformat:"0" }} ₽
            </span>
            <span style="text-decoration: line-through; font-size: 15px; margin-left: 10px;">
              {{ data.old_price|floatformat:"0" }} ₽
            </span>
          </p>
          
          <div class="rating">
            <span style="font-size: 13px;">
              <i class="fas fa-star"></i>
            </span>
            <span style="font-size: 14px;">
              {{data.reviewRating}}
            </span>
          </div>
          
          <p>{{data.website}}</p>
        </div>
      {% empty %}
      {% endfor %}
      <!-- Результат запроса Пиццерии -->
      {% if pizza_results %}
        <div class="row row-2">
          <h2>Пиццерии</h2>
        </div>
      {% endif %}
      {% for data in pizza_results %}
        <div class="col-4">
          
          <a href="{{ data.get_absolute_url }}">
            <img src="{{ data.picture_url }}">
          </a>
          
          <h4>
            <a href="{{ data.get_absolute_url }}">{{ data.title }}</a>
          </h4>
          
          <div class="rating">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
          </div>
          
          <p>{{ data.price }} ₽</p>
          <p>{{data.website}}</p>
          
        </div>
      {% empty %}
      {% endfor %}
    </div>
  {% else %}
    <h1>Корзина</h1>
    {% if wildberries_items %}
      <table id="cart" class="cart-table">
        <thead>
          <tr>
            <th class="cart-title"><p>Вайлдберриз</p></th>
            <th  colspan="5"></th> 
          </tr>
        </thead>
        <tbody>
          {% for item, add_form in wildberries_items %}
            {% with product=item.content_object %}
              <tr class="cart-item">
                <td class="cart-product-image">
                  <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.picture_urls.0 %}{{ product.picture_urls.0}}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="{{ product.title }}">
                  </a>
                </td>
                <td class="cart-product-title">
                  {{ product.title }}
                </td>
                <td class="cart-product-quantity">
                  <form action="{% url 'cart:cart_add_wildberries' product.id %}" method="post" class="quantity-form" data-product-id="{{ product.id }}" data-price-per-item="{{ product.price }}" data-old-price-per-item="{{ product.old_price }}">
                    <button type="button" class="cart-change-btn quantity-change" data-change="-1"><i class="bi bi-dash"></i></button>
                    {{ add_form.quantity }}
                    <button type="button" class="cart-change-btn quantity-change" data-change="1"><i class="bi bi-plus"></i></button>
                    {{ add_form.override }}
                    {% csrf_token %}
                  </form>
                </td>
                <td class="num cart-product-price" data-product-id="{{ product.id }}">{{ item.total_price }} ₽</td>
                <td class="cart-product-old-price" data-product-id="{{ product.id }}">{{ item.total_price_for_old }} ₽</td>
                <td class="cart-product-remove">
                  <form action="{% url 'cart:cart_remove_wildberries' product.id %}" method="post" class="remove-form">
                    <button type="submit" class="remove-button">
                      <i class="bi bi-trash3"></i>
                    </button>
                    {% csrf_token %}
                  </form>
                </td>
              </tr>
            {% endwith %}
          {% endfor %}
          <tr class="cart-total-on-bottom">
            <td class="cart-total-price"><p>Итого</p></td>
            <td colspan=2></td>
            <td class="num total-price">{{ total_price_wildberries }} ₽</td>
            <td class="num total-price-for-old">{{ total_price_for_old_wildberries }} ₽</td>
            <td><a href="{% url 'orders:order_create_wildberries' %}" class="button">Оформить</a></td>
          </tr>
        </tbody>
      </table>
    {% endif %}
    {% if pizzaroni_items %}
      <h2>Пиццарони</h2>    
      {% for item, add_form in pizzaroni_items %}
        <table class="cart">
          <thead><tr>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th></tr>
          </thead>
          <tbody>
            {% with product=item.content_object %}
              <tr>
                <td>
                  <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.picture_url %}{{ product.picture_url}}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                  </a>
                </td>
                <td>
                  {{ product.title }}
                </td>
                <td>
                  <form action="{% url 'cart:cart_add_pizzaroni' product.id %}" method="post">
                    {{ add_form.quantity }}
                    {{ add_form.override }}
                    <input type="submit" value="Обновить">
                    {% csrf_token %}
                  </form>
                </td>
                <td>
                  <form action="{% url 'cart:cart_remove_pizzaroni' product.id %}" method="post">
                    <input type="submit" value="Убрать">
                    {% csrf_token %}
                  </form>
                </td>
                <td class="num">{{ item.total_price }} ₽</td>
              </tr>
            {% endwith %}
          </tbody>
        </table>
      {% endfor %}
      <span>Общая сумма</span>
      <span class="num">{{ total_price_pizzaroni }} ₽</span>
      <a href="{% url 'orders:order_create_pizzaroni' %}" class="cart-order-button">Оформить</a>
    {% endif %}
    <div class="more-actions">
      <a class="load_more" href="{% url 'navigator:product_list' %}">
        <div>
          <button id="load-more">К покупкам</button>
        </div>
      </a>
    </div>
  {% endif %}
{% endblock %}
{% block script %}

document.querySelectorAll('.quantity-form').forEach(form => {
  form.querySelector('input[type="number"]').addEventListener('change', function(e) {
    e.preventDefault(); // Предотвращаем стандартную отправку формы

    let quantity = parseInt(this.value);

    // Устанавливаем ограничение на максимальное количество
    if (quantity > 99) {
      quantity = 99;
      this.value = 99; // Обновляем значение в поле ввода
    }
    const productId = form.dataset.productId;
    const pricePerItem = parseFloat(form.dataset.pricePerItem);
    const oldPricePerItem = parseFloat(form.dataset.oldPricePerItem); // Старая цена за единицу

    // Вычисляем новые цены
    const newTotalPrice = quantity * pricePerItem;
    const newOldTotalPrice = quantity * oldPricePerItem;

    // Обновляем цены в DOM
    document.querySelector(`.cart-product-price[data-product-id="${productId}"]`).textContent = `${newTotalPrice.toFixed(0)} ₽`;
    document.querySelector(`.cart-product-old-price[data-product-id="${productId}"]`).textContent = `${newOldTotalPrice.toFixed(0)} ₽`;

    updateTotalPrice();

    // Функция для обновления общей суммы
    function updateTotalPrice() {
      let totalPrice = 0;
      document.querySelectorAll('.cart-product-price').forEach(price => {
        totalPrice += parseFloat(price.textContent.replace(' ₽', ''));
      });
      // Обновляем общую сумму в DOM
      document.querySelector('.num.total-price').textContent = `${totalPrice.toFixed(0)} ₽`;
      

      let oldtotalPrice = 0;
      document.querySelectorAll('.cart-product-old-price').forEach(price => {
        oldtotalPrice += parseFloat(price.textContent.replace(' ₽', ''));
      });
      document.querySelector('.num.total-price-for-old').textContent = `${oldtotalPrice.toFixed(0)} ₽`;
    }


    // Отправляем AJAX-запрос на сервер
    fetch(form.getAttribute('action'), {
      method: 'POST',
      body: new FormData(form),
      headers: {
        'X-CSRFToken': form.querySelector('[name=csrfmiddlewaretoken]').value,
        'X-Requested-With': 'XMLHttpRequest'
      },
    })
    .then(response => {
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      return response.json();
    })
    .then(data => {
      // Если сервер возвращает обновлённые цены, используйте их для обновления DOM
      // Пример: если сервер возвращает обновлённую общую и старую цену
      // document.querySelector(`.cart-product-price[data-product-id="${productId}"]`).textContent = `${data.new_total_price} ₽`;
      // document.querySelector(`.cart-product-old-price[data-product-id="${productId}"]`).textContent = `${data.new_old_total_price} ₽`;
    })
    .catch(error => {
      console.error('Error:', error);
    });
  });
});


document.querySelectorAll('.quantity-form').forEach(form => {
  form.querySelectorAll('.quantity-change').forEach(button => {
    button.addEventListener('click', function(e) {
      e.preventDefault();
      const quantityInput = form.querySelector('input[type="number"]');
      let quantity = parseInt(quantityInput.value) || 0;
      const change = parseInt(this.dataset.change);

      quantity += change;
      if (quantity < 0) quantity = 0; // Предотвращаем отрицательные значения
      if (quantity > 99) quantity = 99; // Ограничение по максимальному количеству

      quantityInput.value = quantity;

      // Вызываем функцию для обновления цен
      updatePrices(form, quantity);
    });
  });

  function updatePrices(form, quantity) {
    const productId = form.dataset.productId;
    const pricePerItem = parseFloat(form.dataset.pricePerItem);
    const oldPricePerItem = parseFloat(form.dataset.oldPricePerItem);

    const newTotalPrice = quantity * pricePerItem;
    const newOldTotalPrice = quantity * oldPricePerItem;

    document.querySelector(`.cart-product-price[data-product-id="${productId}"]`).textContent = `${newTotalPrice.toFixed(0)} ₽`;
    document.querySelector(`.cart-product-old-price[data-product-id="${productId}"]`).textContent = `${newOldTotalPrice.toFixed(0)} ₽`;

    // Обновляем общую сумму
    updateTotalPrice();
    sendQuantityUpdate(productId, quantity);
  }

  function updateTotalPrice() {
    let totalPrice = 0;
    document.querySelectorAll('.cart-product-price').forEach(price => {
      totalPrice += parseFloat(price.textContent.replace(' ₽', ''));
    });
    document.querySelector('.num.total-price').textContent = `${totalPrice.toFixed(0)} ₽`;
        
    let oldtotalPrice = 0;
    document.querySelectorAll('.cart-product-old-price').forEach(price => {
      oldtotalPrice += parseFloat(price.textContent.replace(' ₽', ''));
    });
    document.querySelector('.num.total-price-for-old').textContent = `${oldtotalPrice.toFixed(0)} ₽`;
  }
  
  function sendQuantityUpdate(productId, quantity) {
  fetch(form.getAttribute('action'), {
      method: 'POST',
      body: new FormData(form),
      headers: {
        'X-CSRFToken': form.querySelector('[name=csrfmiddlewaretoken]').value,
        'X-Requested-With': 'XMLHttpRequest'
      },
    })
  .then(response => {
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    return response.json();
  })
  .then(data => {
    console.log('Quantity updated successfully');
  })
  .catch(error => {
    console.error('Error:', error);
  });
}
});


{% endblock %}