Solidus/Solidus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
	path('account/', include('account.urls', namespace='account')),
    path('', include('navigator.urls', namespace='navigator')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Solidus/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('wildberries/add/<int:product_id>/', views.cart_add_wildberries, name='cart_add_wildberries'),
    path('pizzaroni/add/<int:product_id>/', views.cart_add_pizzaroni, name='cart_add_pizzaroni'),
    path('pizzaroni/remove/<int:product_id>/', views.cart_remove_pizzaroni, name='cart_remove_pizzaroni'),
    path('wildberries/remove/<int:product_id>/', views.cart_remove_wildberries, name='cart_remove_wildberries'),
]

Solidus/navigator/urls.py
from django.urls import path
from . import views

app_name = 'navigator'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('market_products/', views.market_products, name='market_products'),
    path('pizza_products/', views.pizza_products, name='pizza_products'),
    path('market/<int:id>/<slug:slug>/', views.wildberries_detail, name='wildberries_detail'),
    path('pizza/<int:id>/<slug:slug>/', views.pizzaroni_detail, name='pizzaroni_detail'),
]

Solidus/navigator/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
# Create your models here.
    

class Pizzaroni(models.Model):
	title = models.CharField(max_length=255, null=True)
	slug = models.SlugField(max_length=200, 
							db_index=True, null=True)
	picture_url = models.URLField(null=True)
	old_price = models.DecimalField(max_digits=10,
									decimal_places=0, null=True)
	price = models.DecimalField(max_digits=10, 
								decimal_places=2, null=True)
	description = models.TextField(blank=True, null=True)
	website = models.CharField(max_length=100, null=True)


	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('navigator:pizzaroni_detail', args=[self.id, self.slug])
    
    
class Wildberries(models.Model):
	title = models.CharField(max_length=255, null=True)
	slug = models.SlugField(max_length=200, 
							db_index=True, null=True)
	picture_urls = ArrayField(models.CharField(max_length=200), null=True)
	old_price = models.DecimalField(max_digits=10,
									decimal_places=0, null=True)
	price = models.DecimalField(max_digits=10, 
								decimal_places=0, null=True)
	reviewRating = models.DecimalField(max_digits=10, 
								decimal_places=1, null=True)
	description = models.TextField(blank=True, null=True)
	website = models.CharField(max_length=100, null=True)
	photo_count = models.DecimalField(max_digits=10, decimal_places=0, null=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('navigator:wildberries_detail', args=[self.id, self.slug])
	

class Ozon(models.Model):
	title = models.CharField(max_length=255, null=True)
	slug = models.SlugField(max_length=200, 
							db_index=True, null=True)
	picture_urls = ArrayField(models.CharField(max_length=200), null=True)
	old_price = models.DecimalField(max_digits=10,
									decimal_places=0, null=True)
	price = models.DecimalField(max_digits=10, 
								decimal_places=0, null=True)
	reviewRating = models.DecimalField(max_digits=10, 
								decimal_places=1, null=True)
	description = models.TextField(blank=True, null=True)
	website = models.CharField(max_length=100, null=True)
	photo_count = models.DecimalField(max_digits=10, decimal_places=0, null=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('navigator:ozon_detail', args=[self.id, self.slug])

Solidus/navigator/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'search-input', 'type':'text', 'placeholder':'Поиск...'})
    )

Solidus/navigator/views.py
from django.shortcuts import render, get_object_or_404
from .models import Pizzaroni, Wildberries, Ozon
from .forms import SearchForm
from django.contrib.postgres.search import TrigramSimilarity
#from .parser import parse_website_data
import json
from django.conf import settings
import os
from cart.forms import CartAddProductForm





#тут все для запроса онлайн
import requests
from django.core.management.base import BaseCommand
from bs4 import BeautifulSoup
from navigator.models import Wildberries
import json


    
def handle(url):

	headers = {
		'Accept':'*/*',
		'Accept-Language':'ru,en;q=0.9',
		'Connection':'keep-alive',
		'Origin':'https://www.wildberries.ru',
		'Referer':'https://www.wildberries.ru/catalog/elektronika/avtoelektronika',
		'Sec-Fetch-Dest':'empty',
		'Sec-Fetch-Mode':'cors',
		'Sec-Fetch-Site':'cross-site',
		'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.660 YaBrowser/23.9.5.660 Yowser/2.5 Safari/537.36',
		'sec-ch-ua':'^\^"Chromium^\^";v=^\^"116^\^", ^\^"Not)A;Brand^\^";v=^\^"24^\^", ^\^"YaBrowser^\^";v=^\^"23^\^"',
		'sec-ch-ua-mobile':'?0',
		'sec-ch-ua-platform':'^\^"Windows^\^"',

	}
	url = f'https://search.wb.ru/exactmatch/ru/male/v4/search?TestGroup=no_test&TestID=no_test&appType=1&curr=rub&dest=-1186630&query={url}&resultset=catalog&sort=popular&spp=29&suppressSpellcheck=false&uclusters=0'

	for page in range(1, 6):
		resp = requests.get(url=f'{url}&page={page}', headers=headers)

		resp = resp.json()
		products_row = resp.get('data', {}).get('products', None)
		products = []
		if products_row != None and len(products_row)>0:
			for product in products_row:
				products.append({
					'title': product.get('name', None),
					'slug': product.get('id', None),
					'old_price': float(product.get('priceU', None))/100 if product.get('priceU', None) != None else None,
					'price': float(product.get('salePriceU', None))/100 if product.get('salePriceU', None) != None else None,
					'description': None,
					'picture_urls' : None,
					'website': 'Wildberries',
					'reviewRating': product.get('reviewRating', None),
					'photo_count': None
				})




		def add_url(d, x_str, p_id, d_url):
			product_url = f'https://basket-{x_str}.wb.ru/vol{p_id[:l-5]}/part{p_id[:l-3]}/{p_id}/info/ru/card.json'
			product_header = {
				"sec-ch-ua": '^\^"Chromium^\^";v=^\^"116^\^", ^\^"Not)A;Brand^\^";v=^\^"24^\^", ^\^"YaBrowser^\^";v=^\^"23^\^"', 
				"Referer": f"https://www.wildberries.ru/catalog/{p_id}/detail.aspx", 
				"sec-ch-ua-mobile": "?0", 
				"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.660 YaBrowser/23.9.5.660 Yowser/2.5 Safari/537.36", 
				"sec-ch-ua-platform": '^\^"Windows^\^"'
			}
			resp = requests.get(url=product_url, headers=product_header)
			resp = resp.json()
			description = resp.get('description', None)
			media_count = resp.get('media', {}).get('photo_count', None)
			products[d]['description'] = description
			products[d]['photo_count'] = media_count
			for x in range(2, media_count+1):
				products[d]['picture_urls'] += [d_url[:-6]+str(x)+'.webp']



		session = requests.Session()
		for d in range(len(products)):
			p_id = str(products[d]['slug'])
			l = len(p_id)
			
			if 0<=int(p_id[:l-5])<=143:
				x_str = '01' 
			elif 144<=int(p_id[:l-5])<=287:
				x_str = '02'
			elif 288<=int(p_id[:l-5])<=431:
				x_str = '03'
			elif 432<=int(p_id[:l-5])<=719:
				x_str = '04'
			elif 720<=int(p_id[:l-5])<=1007:
				x_str = '05'
			elif 1008<=int(p_id[:l-5])<=1061:
				x_str = '06'
			elif 1062<=int(p_id[:l-5])<=1115:
				x_str = '07'
			elif 1116<=int(p_id[:l-5])<=1169:
				x_str = '08'
			elif 1170<=int(p_id[:l-5])<=1313:
				x_str = '09'
			elif 1314<=int(p_id[:l-5])<=1601:
				x_str = '10'
			elif 1602<=int(p_id[:l-5])<=1655:
				x_str = '11'
			elif 1656<=int(p_id[:l-5])<=1919:
				x_str = '12'
			elif 1920<=int(p_id[:l-5])<=2045:
				x_str = '13'
			elif 2046<=int(p_id[:l-5])<=2189:
				x_str = '14'
			else:
				x_str = '15'
			d_url = f'https://basket-{x_str}.wb.ru/vol{p_id[:l-5]}/part{p_id[:l-3]}/{p_id}/images/big/1.webp'
			products[d]['picture_urls'] = [d_url]
			
			add_url(d, x_str, p_id, d_url)



		res = []
		for d in products:
			parsed_data = Wildberries.objects.create(title=d['title'], slug=d['slug'], picture_urls=d['picture_urls'], old_price=d['old_price'], price=d['price'], description=d['description'], website=d["website"], reviewRating=d['reviewRating'], photo_count=d['photo_count'])
			parsed_data.save()
			res.append(parsed_data)


		return res













def product_list(request, category_slug=None):
	pizza_datas = Pizzaroni.objects.all()[:24]
	market_datas = Wildberries.objects.all()[:24]


	form = SearchForm()
	query = None
	pizza_results = []
	market_results = []
	if 'query' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			query = form.cleaned_data['query']
			market_results = handle(query) #вызываем онлайн запрос
			pizza_results = Pizzaroni.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
#			market_results = Wildberries.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')



	return render(request, 'navigator/product/product.html', 
				 {'pizza_datas':pizza_datas,
				 'market_datas':market_datas,
				 'form':form, 
				 'query':query,
				 'market_results':market_results,
				 'pizza_results':pizza_results,})


def pizzaroni_detail(request, id, slug):
    parsed_data = get_object_or_404(Pizzaroni, id=id, slug=slug)
    
    cart_product_form = CartAddProductForm()
    
    form = SearchForm()
    query = None
    pizza_results = []
    market_results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            pizza_results = Pizzaroni.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
            market_results = Wildberries.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')

    return render(request, 'navigator/product/pizzaroni_detail.html', {'parsed_data':parsed_data,
                                                                  'form':form, 
                                                                  'query':query,
                                                                  'market_results':market_results,
                                                                  'pizza_results':pizza_results,
																  'cart_product_form':cart_product_form})

def wildberries_detail(request, id, slug):
    market_data = get_object_or_404(Wildberries, id=id, slug=slug)
    photo_count = market_data.photo_count
    
    cart_product_form = CartAddProductForm()
    
    form = SearchForm()
    query = None
    pizza_results = []
    market_results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            pizza_results = Pizzaroni.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
            market_results = Wildberries.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
    
    return render(request, 'navigator/product/wildberries_detail.html', {'market_data':market_data, 
                                                                  'range':range(0, int(photo_count)),
                                                                  'form':form, 
                                                                  'query':query,
                                                                  'market_results':market_results,
                                                                  'pizza_results':pizza_results,
                                                                  'cart_product_form':cart_product_form})

def ozon_detail(request, id, slug):
    market_data = get_object_or_404(Ozon, id=id, slug=slug)
    photo_count = market_data.photo_count
    
    cart_product_form = CartAddProductForm()
    
    form = SearchForm()
    query = None
    pizza_results = []
    market_results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            pizza_results = Pizzaroni.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
            market_results = Wildberries.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
    
    return render(request, 'navigator/product/wildberries_detail.html', {'market_data':market_data, 
                                                                  'range':range(0, int(photo_count)),
                                                                  'form':form, 
                                                                  'query':query,
                                                                  'market_results':market_results,
                                                                  'pizza_results':pizza_results,
                                                                  'cart_product_form':cart_product_form})


    
def pizza_products(request):
        pizza_datas = Pizzaroni.objects.all()
        
        form = SearchForm()
        query = None
        pizza_results = []
        market_results = []
        if 'query' in request.GET:
            form = SearchForm(request.GET)
            if form.is_valid():
                query = form.cleaned_data['query']

Solidus/navigator/templates/navigator/product/example.html
<div class = "card-wrapper">
  <div class = "card">
    <!-- card left -->
    <div class = "product-imgs">
      <div class = "img-display">
        <div class = "img-showcase">
          <img src = "https://fadzrinmadu.github.io/hosted-assets/product-detail-page-design-with-image-slider-html-css-and-javascript/shoe_1.jpg" alt = "shoe image">
          <img src = "https://fadzrinmadu.github.io/hosted-assets/product-detail-page-design-with-image-slider-html-css-and-javascript/shoe_2.jpg" alt = "shoe image">
          <img src = "https://fadzrinmadu.github.io/hosted-assets/product-detail-page-design-with-image-slider-html-css-and-javascript/shoe_3.jpg" alt = "shoe image">
          <img src = "https://fadzrinmadu.github.io/hosted-assets/product-detail-page-design-with-image-slider-html-css-and-javascript/shoe_4.jpg" alt = "shoe image">
        </div>
      </div>
      <div class = "img-select">
        <div class = "img-item">
          <a href = "#" data-id = "1">
            <img src = "https://fadzrinmadu.github.io/hosted-assets/product-detail-page-design-with-image-slider-html-css-and-javascript/shoe_1.jpg" alt = "shoe image">
          </a>
        </div>
        <div class = "img-item">
          <a href = "#" data-id = "2">
            <img src = "https://fadzrinmadu.github.io/hosted-assets/product-detail-page-design-with-image-slider-html-css-and-javascript/shoe_2.jpg" alt = "shoe image">
          </a>
        </div>
        <div class = "img-item">
          <a href = "#" data-id = "3">
            <img src = "https://fadzrinmadu.github.io/hosted-assets/product-detail-page-design-with-image-slider-html-css-and-javascript/shoe_3.jpg" alt = "shoe image">
          </a>
        </div>
        <div class = "img-item">
          <a href = "#" data-id = "4">
            <img src = "https://fadzrinmadu.github.io/hosted-assets/product-detail-page-design-with-image-slider-html-css-and-javascript/shoe_4.jpg" alt = "shoe image">
          </a>
        </div>
      </div>
    </div>
    <!-- card right -->
    <div class = "product-content">
      <h2 class = "product-title">nike shoes</h2>
      <a href = "#" class = "product-link">visit nike store</a>
      <div class = "product-rating">
        <i class = "fas fa-star"></i>
        <i class = "fas fa-star"></i>
        <i class = "fas fa-star"></i>
        <i class = "fas fa-star"></i>
        <i class = "fas fa-star-half-alt"></i>
        <span>4.7(21)</span>
      </div>

      <div class = "product-price">
        <p class = "last-price">Old Price: <span>$257.00</span></p>
        <p class = "new-price">New Price: <span>$249.00 (5%)</span></p>
      </div>

      <div class = "product-detail">
        <h2>about this item: </h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo eveniet veniam tempora fuga tenetur placeat sapiente architecto illum soluta consequuntur, aspernatur quidem at sequi ipsa!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, perferendis eius. Dignissimos, labore suscipit. Unde.</p>
        <ul>
          <li>Color: <span>Black</span></li>
          <li>Available: <span>in stock</span></li>
          <li>Category: <span>Shoes</span></li>
          <li>Shipping Area: <span>All over the world</span></li>
          <li>Shipping Fee: <span>Free</span></li>
        </ul>
      </div>

      <div class = "purchase-info">
        <input type = "number" min = "0" value = "1">
        <button type = "button" class = "btn">
          Add to Cart <i class = "fas fa-shopping-cart"></i>
        </button>
        <button type = "button" class = "btn">Compare</button>
      </div>

      <div class = "social-links">
        <p>Share At: </p>
        <a href = "#">
          <i class = "fab fa-facebook-f"></i>
        </a>
        <a href = "#">
          <i class = "fab fa-twitter"></i>
        </a>
        <a href = "#">
          <i class = "fab fa-instagram"></i>
        </a>
        <a href = "#">
          <i class = "fab fa-whatsapp"></i>
        </a>
        <a href = "#">
          <i class = "fab fa-pinterest"></i>
        </a>
      </div>
    </div>
  </div>
</div>





<!-- ПОИСКОВАЯ ХУЙНЯ -->
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ваш Сайт</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <div class="navbar">
            <div class="brand-title">Название Сайта</div>
            <a href="#" class="toggle-button">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </a>
            <div class="navbar-links">
                <ul>
                    <li><a href="#">Главная</a></li>
                    <li><a href="#">О нас</a></li>
                    <li><a href="#">Сервисы</a></li>
                    <li><a href="#">Контакты</a></li>
                </ul>
            </div>
            <div class="search-container">
                <form action="/search">
                    <input type="text" placeholder="Поиск..." name="search">
                    <button type="submit">🔍</button>
                </form>
            </div>
        </div>
    </header>
</body>
</html>


.header {
    background-color: #f3f3f3;
    box-shadow: 0 2px 4px 0 rgba(0,0,0,.2);
}

.navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 20px;
    flex-wrap: wrap; /* Добавлено для поддержания элементов в одной линии */
}

.brand-title {
    font-size: 24px;
    margin: 0;
    flex-basis: 100%; /* Позволяет заголовку занимать всю ширину на мобильных устройствах */
}

.navbar-links ul {
    margin: 0;
    padding: 0;
    list-style: none;
    display: flex; /* Для горизонтального расположения меню */
    flex-basis: 100%; /* Позволяет меню занимать всю ширину на мобильных устройствах */
    justify-content: center; /* Центрирует меню */
}

.navbar-links li {
    display: inline;
    margin-left: 20px;
}

.navbar-links a {
    text-decoration: none;
    color: #333;
}

.navbar-links a:hover {
    color: #007bff;
}

.toggle-button {
    display: none;
    flex-direction: column;
    justify-content: space-between;
    width: 30px;
    height: 21px;
}

.toggle-button .bar {
    height: 3px;
    width: 100%;
    background-color: #333;
    border-radius: 10px;
}

.search-container {
    display: flex;
    align-items: center;
    flex-basis: 100%; /* Для занимания всей ширины на мобильных устройствах */
}

.search-container input[type="text"] {
    flex-grow: 1; /* Позволяет поисковой строке растягиваться */
    padding: 7px;
    margin-right: 10px;
    border: 1px solid #ddd;
    border-radius: 4px;
}

.search-container button {
    padding: 7px;
    background-color: #ddd;
    border: none;
    cursor: pointer;
    border-radius: 4px;
}

/* Адаптивность */
@media (max-width: 800px) {
    .navbar {
        flex-direction: column;
        align-items: flex-start;
    }

    .navbar-links {
        display: none; /* Скрытие меню до активации гамбургера */
        width: 100%;
    }

    .navbar-links ul {
        flex-direction: column; /* Элементы меню располагаются вертикально */
    }

    .toggle-button {
        display: flex;
    }

    .search-container {
        width: 100%;
        justify-content: center;
        margin-top: 10px;
    }
}

/* Показывать меню при клике на гамбургер */
.toggle-button:focus + .navbar-links,
.toggle-button:active + .navbar-links {
    display: flex; /* Отображение меню при активации гамбургера */
    flex-direction: column;
    align-items: center;
}












<h2>Вайлдберриз</h2>
       {% for item, add_form in wildberries_items %}
            <table class="cart">
                <thead><tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th></tr>
                </thead>
                <tbody>
                    {% with product=item.content_object %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.picture_urls.0 %}{{ product.picture_urls.0}}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                            </a>
                        </td>
                        <td>
                          {{ product.title }}
                        </td>
                        <td>
						  <form action="{% url 'cart:cart_add_wildberries' product.id %}" method="post">
							{{ add_form.quantity }}
							{{ add_form.override }}
							<input type="submit" value="Обновить">
							{% csrf_token %}
						  </form>
						</td>
                        <td>
                            <form action="{% url 'cart:cart_remove_wildberries' product.id %}" method="post">
                              <input type="submit" value="Убрать">
                              {% csrf_token %}
                            </form>
                        </td>
                        <td class="num">{{ item.total_price }} ₽</td>
                        <td class="num">{{ item.total_price_for_old }} ₽</td>
                    </tr>
                        {% endwith %}
                </tbody>
            </table>

Solidus/navigator/templates/navigator/product/product.html
{% extends "navigator/base.html" %}
{% load static %}

{% block title %}
    Главная
{% endblock %}


{% block content %}
  {% if query %}
    <!-- Результат запроса Маркетплейсов -->
    <div class="row">
      {% if market_results %}
        <div class="row row-2">
          <h2>Маркетплейсы</h2>
        </div>
      {% endif %}
      {% for data in market_results %}
        <div class="col-4">
          
          <a href="{{ data.get_absolute_url }}">
            <img src="{{ data.picture_urls.0 }}">
          </a>
          
          <p>
            <a href="{{ data.get_absolute_url }}">
              {{ data.title|truncatechars:30 }}
            </a>
          </p>
          
          <p style="margin-top: -10px; margin-bottom: 3px;">
            <span style="font-size: 17px; color: black;">
              {{ data.price|floatformat:"0" }} ₽
            </span>
            <span style="text-decoration: line-through; font-size: 15px; margin-left: 10px;">
              {{ data.old_price|floatformat:"0" }} ₽
            </span>
          </p>
          
          <div class="rating">
            <span style="font-size: 13px;">
              <i class="fas fa-star"></i>
            </span>
            <span style="font-size: 14px;">
              {{data.reviewRating}}
            </span>
          </div>
          
          <p>{{data.website}}</p>
        </div>
      {% empty %}
      {% endfor %}
      <!-- Результат запроса Пиццерии -->
      {% if pizza_results %}
        <div class="row row-2">
          <h2>Пиццерии</h2>
        </div>
      {% endif %}
      {% for data in pizza_results %}
        <div class="col-4">
          
          <a href="{{ data.get_absolute_url }}">
            <img src="{{ data.picture_url }}">
          </a>
          
          <h4>
            <a href="{{ data.get_absolute_url }}">{{ data.title }}</a>
          </h4>
          
          <div class="rating">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
          </div>
          
          <p>{{ data.price }} ₽</p>
          <p>{{data.website}}</p>
          
        </div>
      {% empty %}
      {% endfor %}
    </div>
  {% else %}
    <!-- Результат данных Маркетплейсов -->
    <div class="row row-2">
      <h2>Маркетплейсы</h2>
    </div>

    <div class="row">
      {% for data in market_datas %}
        <div class="col-4">
          
          <a href="{{ data.get_absolute_url }}">
            <img src="{{ data.picture_urls.0 }}">
          </a>
          
          <p>
            <a href="{{ data.get_absolute_url }}">
              {{ data.title|truncatechars:30 }}
            </a>
          </p>
          
          <p style="margin-top: -10px; margin-bottom: 3px;">
            <span style="font-size: 17px; color: black;">
              {{ data.price }} ₽
            </span>
            <span style="text-decoration: line-through; font-size: 15px; margin-left: 10px;">
              {{ data.old_price }} ₽
            </span>
          </p>
          
          <div class="rating">
            <span style="font-size: 13px;">
              <i class="fas fa-star"></i>
            </span>
            <span style="font-size: 14px;">
              {{data.reviewRating}}
            </span>
          </div>
          
          <p>{{data.website}}</p>
          
        </div>
      {% endfor %}
      <div class="more-actions">
        <a class="load_more" href="{% url 'navigator:market_products' %}">
          <div>
            <button id="load-more">Загрузить больше</button>
          </div>
        </a>
      </div>
      <!-- Результат данных Пиццерии -->
      <div class="row row-2">
        <h2>Пиццерии</h2>
      </div>
      
      {% for data in pizza_datas %}
        <div class="col-4">
          
          <a href="{{ data.get_absolute_url }}">
            <img src="{{ data.picture_url }}">
          </a>
          <h4>
            <a href="{{ data.get_absolute_url }}">{{ data.title }}</a>
          </h4>
          
          <div class="rating">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
          </div>
          
          <p>{{ data.price }} ₽</p>
          <p>{{data.website}}</p>
          
        </div>
      {% endfor %}
      <div class="more-actions">
        <a class="load_more" href="{% url 'navigator:pizza_products' %}">
          <div>
            <button id="load-more">Загрузить больше</button>
          </div>
        </a>
      </div>
    </div>
  {% endif %}
{% endblock %}